name: Fetch V2Ray Subscriptions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  fetch_subscriptions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Run subscription fetch script
        run: python script.py
